" =============================================================================
" SETTINGS
" =============================================================================
filetype plugin indent on
set nocompatible
set number
set laststatus=2
set ruler
set scrolloff=5
set sidescroll=1
set sidescrolloff=2
set display+=lastline
set display+=truncate
set listchars=tab:▸\ ,eol:¬,space:·,trail:~,extends:>,precedes:<

set term=xterm-256color
set t_Co=256

set mouse=a
set background=dark

syntax enable
colorscheme jellybeans
"colorscheme catppuccin
set incsearch
set hlsearch

set backspace=indent,eol,start
set smarttab
set expandtab
set shiftwidth=4
set tabstop=4
set formatoptions+=j

set history=1000
set autoread
set sessionoptions-=options
set viewoptions-=options
set tabpagemax=50

" Don't scan included files for autocomplete (slow)
set complete-=i

" Treat numbers with leading zeros as decimal, not octal
set nrformats-=octal

if v:version >= 902
    " Vim 9.2+: Use popup menu and let plugins handle mappings
    set completeopt=menuone,popup,noinsert
    set infercase              " Smart case matching 
    " set wildmode=noselect:lastused,full
    set wildmode=longest:lastused,full:noselect
    "set wildmode=full
    set wildoptions=pum
    set wildcharm=<C-@>
else
    " Older Vim
    " Basic completion auto-completion improvements
	set completeopt=menu,menuone
	set completeopt+=noinsert 
	set wildmenu " Command line completion menu 
	
    " Make Enter select completion instead of inserting newline
    inoremap <expr> <CR> pumvisible() ? "\<C-y>" : "\<CR>"
    
    " Use Tab/S-Tab to navigate
    inoremap <expr> <Tab> pumvisible() ? "\<C-n>" : "\<Tab>"
    inoremap <expr> <S-Tab> pumvisible() ? "\<C-p>" : "\<S-Tab>"
endif
    
" Make escape key more responsive (100ms timeout for key codes)
if !has('nvim') && &ttimeoutlen == -1
  set ttimeout
  set ttimeoutlen=100
endif

" Save global variables (g:UPPERCASE) in viminfo
if !empty(&viminfo)
  set viminfo^=!
endif


" =============================================================================
" KEY BINDINGS
" =============================================================================

let mapleader = " "

" Clear search highlighting with Ctrl-L (also redraws screen)
if maparg('<C-L>', 'n') ==# ''
  nnoremap <silent> <C-L> :nohlsearch<C-R>=has('diff')?'<Bar>diffupdate':''<CR><CR><C-L>
endif

" Make Ctrl-U and Ctrl-W create undo break points in insert mode
if empty(mapcheck('<C-U>', 'i'))
  inoremap <C-U> <C-G>u<C-U>
endif
if empty(mapcheck('<C-W>', 'i'))
  inoremap <C-W> <C-G>u<C-W>
endif

nnoremap <Leader>* ciw*<C-r>"*<Esc>
nnoremap <Leader>" ciw"<C-r>""<Esc>
nnoremap <Leader>' ciw'<C-r>"'<Esc>
nnoremap <Leader>_ ciw_<C-r>"_<Esc>
nnoremap <Leader>( ciw(<C-r>")<Esc>
nnoremap <Leader>[ ciw[<C-r>"]<Esc>
nnoremap <Leader>{ ciw{<C-r>"}<Esc>

" Toggle paste mode to prevent auto-indentation when pasting
set pastetoggle=<F2>

" Readline-like bindings for command mode
cnoremap <C-a> <Home>
cnoremap <C-e> <End>
cnoremap <C-p> <Up>
cnoremap <C-n> <Down>

" =============================================================================
" FUNCTIONS & COMMANDS
" =============================================================================

" Auto-pair brackets, braces, and parentheses intelligently
function! ConditionalPairMap(open, close) abort
    let line = getline('.')
    let col = col('.')
    if col < col('$') || stridx(line, a:close, col + 1) != -1
        return a:open
    else
        return a:open . a:close . repeat("\<left>", len(a:close))
    endif
endfunction
inoremap <expr> ( ConditionalPairMap('(', ')')
inoremap <expr> { ConditionalPairMap('{', '}')
inoremap <expr> [ ConditionalPairMap('[', ']')

" Diff current buffer against saved file
if exists(":DiffOrig") != 2
  command DiffOrig vert new | set bt=nofile | r ++edit # | 0d_
        \ | diffthis | wincmd p | diffthis
endif

" =============================================================================
" PLUGINS & EXTENSIONS
" =============================================================================

" Improve shell script syntax highlighting (use POSIX)
if !exists('g:is_posix') && !exists('g:is_bash') && !exists('g:is_kornshell') && !exists('g:is_dash')
  let g:is_posix = 1
endif

" Load matchit plugin for enhanced % matching
if !exists('g:loaded_matchit') && findfile('plugin/matchit.vim', &rtp) ==# ''
  runtime! macros/matchit.vim
endif

" Enable :Man command for reading man pages in Vim
if exists(':Man') != 2 && !exists('g:loaded_man') && &filetype !=? 'man' && !has('nvim')
  runtime ftplugin/man.vim
endif
